In [74]:
from qubolite import qubo
import numpy as np

In [75]:
import sys
sys.path.insert(1, '/Users/linusrandud/Documents/UoM/ERP/MscDissertation/Deep-Opt')

In [76]:
import torch

from COProblems.MKP import MKP
from COProblems.QUBO import QUBO
from Models.DOAE import DOAE
from OptimAE import OptimAEHandler

In [77]:
# Highly recommended to keep as cpu for problems of size <= 100
device="cpu"
print(device)
device = torch.device(device)

cpu


In [78]:
problem = QUBO("/Users/linusrandud/Documents/UoM/ERP/MscDissertation/data/qubo/other.txt", 0, device)

Instance has been loaded


In [79]:
# original

# a = [13, 23, 16, 20]
# solution should be [0, 0, 1, 1] or [1, 1, 0, 0]

In [80]:
problem.Q.detach().cpu().numpy()

array([[11., 10., 20.,  0., 20.,  0.],
       [10., 12.,  0., 20., 10., 20.],
       [20.,  0., 26., 10., 20.,  0.],
       [ 0., 20., 10., 27.,  0., 20.],
       [20., 10., 20.,  0., 11., 10.],
       [ 0., 20.,  0., 20., 10., 12.]], dtype=float32)

In [81]:
np.triu(problem.Q.detach().cpu().numpy())

array([[11., 10., 20.,  0., 20.,  0.],
       [ 0., 12.,  0., 20., 10., 20.],
       [ 0.,  0., 26., 10., 20.,  0.],
       [ 0.,  0.,  0., 27.,  0., 20.],
       [ 0.,  0.,  0.,  0., 11., 10.],
       [ 0.,  0.,  0.,  0.,  0., 12.]], dtype=float32)

In [82]:
Q = problem.Q.detach().cpu().numpy()

In [83]:
from qubolite.solving import brute_force, local2_descent, local2_descent_search, simulated_annealing

In [84]:
Q_ = qubo(Q)
# brute_force(Q_)

In [85]:
local2_descent(Q_)

qubo_solution(x=array([False, False, False, False, False, False]), energy=0.0)

In [86]:
local2_descent_search(Q_)

qubo_solution(x=array([0., 0., 0., 0., 0., 0.]), energy=0.0)

In [87]:
simulated_annealing(Q_)

Init. temp. automatically set to 6956.0933


(array([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [88]:
def evaluate_qubo(Q):
    n = Q.shape[0]
    min_value = float('inf')
    best_x = None
    
    for i in range(2**n):
        x = np.array(list(map(int, bin(i)[2:].zfill(n))))
        value = x.T @ Q @ x
        if value < min_value:
            min_value = value
            best_x = x
    
    return best_x, min_value

In [89]:
evaluate_qubo(Q)

(array([0, 0, 0, 0, 0, 0]), 0.0)

In [90]:
bin(10)

'0b1010'