In [41]:
from qubolite import qubo
import numpy as np

In [19]:
import sys
sys.path.insert(1, '/Users/linusrandud/Documents/UoM/ERP/MscDissertation/Deep-Opt')

In [20]:
import torch

from COProblems.MKP import MKP
from COProblems.QUBO import QUBO
from Models.DOAE import DOAE
from OptimAE import OptimAEHandler

In [21]:
# Highly recommended to keep as cpu for problems of size <= 100
device="cpu"
print(device)
device = torch.device(device)

cpu


In [31]:
problem = QUBO("/Users/linusrandud/Documents/UoM/ERP/MscDissertation/data/qubo/qubo_problem_small.txt", 0, device)

Instance has been loaded


In [32]:
# original

# a = [13, 23, 16, 20]
# solution should be [0, 0, 1, 1] or [1, 1, 0, 0]

In [33]:
problem.Q.detach().cpu().numpy()

array([[-169., -598., -416., -520.],
       [-598., -529., -736., -920.],
       [-416., -736., -256., -640.],
       [-520., -920., -640., -400.]], dtype=float32)

In [42]:
np.triu(problem.Q.detach().cpu().numpy())

array([[-169., -598., -416., -520.],
       [   0., -529., -736., -920.],
       [   0.,    0., -256., -640.],
       [   0.,    0.,    0., -400.]], dtype=float32)

In [43]:
Q = qubo(np.triu(problem.Q.detach().cpu().numpy()))

In [44]:
problem.Q.detach().cpu().numpy().shape

(4, 4)

In [45]:
from qubolite.solving import brute_force

In [46]:
x_min, value = brute_force(Q)

In [47]:
value

-169.0

In [48]:
x_min

array([1., 0., 0., 0.])